root:
    true
env:
    browser: true
    es2021: true
    vue/setup-compiler-macros: true
extends:
    - eslint:recommended
    - plugin:vue/vue3-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:storybook/recommended
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
    parser: '@typescript-eslint/parser'
    ecmaVersion: latest
    sourceType: module
plugins:
    - vue
    - '@typescript-eslint'
rules:
    vue/no-v-html: off
    indent:
        - error
        - 2
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
    object-curly-spacing:
        - error
        - always
    vue/multi-word-component-names: off
