export { default as UIButton } from '@/components/UIButton/UIButton.vue'
export { default as FilterBlock } from '@/components/FilterBlock/FilterBlock.vue'
export { default as NewBlock } from '@/components/NewBlock/NewBlock.vue'
export { default as NavigationMenu } from '@/components/NavigationMenu/NavigationMenu.vue'
export { default as UISlider } from '@/components/UISlider/UISlider.vue'
export { default as UIInput } from '@/components/UIInput/UIInput.vue'
export { default as AppSocial } from '@/components/AppSocial/AppSocial.vue'
export { default as SearchBar } from '@/components/SearchBar/SearchBar.vue'
